
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  CURRENT_BRANCH: ${{ github.ref_name }}
jobs:
  CI:
    if: contains(github.event.head_commit.message, 'deploy')
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
        env:
          CI: false

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "build/*"
          target: "/var/www/findmybmw"


      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo '${{ secrets.PASSWORD }}' | sudo -S systemctl restart nginx
